id: pr_reviewer
namespace: hackathon

inputs:
  - id: payload
    type: JSON
    description: "The raw JSON data from GitHub"

triggers:
  - id: github_webhook
    type: io.kestra.core.models.triggers.types.Webhook
    key: hackathon_secret

tasks:
  - id: run_reviewer
    type: io.kestra.core.tasks.scripts.Bash
    
    # Environment variables passed to the Python script
    env:
      # Pass the raw GitHub payload into the script
      GITHUB_PAYLOAD: "{{ trigger.body | toJson }}"
      
      # Force Python to print logs immediately (for better debugging)
      PYTHONUNBUFFERED: "1" 
      
      # CRITICAL: Pass the Kestra execution URL (for Status Check / Merge Block)
      KESTRA_EXECUTION_URL: "{{ execution.webhookUrl }}" 
      
    commands:
      # Start the Python script using the unbuffered flag for immediate output
      - |
        echo "--- STARTING AI REVIEWER SCRIPT ---"
        python3 -u /app/scripts/reviewer.py
